name: publish-release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: fkmatsuda.dev-oss
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
      - name: Publish package
        run: |
          echo "${VERSION}"
          mvn versions:set -DnewVersion=$VERSION
          mvn versions:commit
          mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.6.0:exec
          mvn clean deploy -Dmaven.test.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_TOKEN }}